Force Erlang evaluation when specified
nerves-project/nerves_ssh pull request #29
Opened 2021-06-06 18:48 UTC by fhunleth

The ssh daemon's exec logic determines whether to run the erlang
evaluator based on whether the shell was specified and exec was not.
Adding an evaluator here isn't much code and ensures that the Erlang
evaluator is called.

2021-06-07 14:04 UTC, jjcarstens requested changes
Looks like there is a bad type and matched return in `erl_scan`

2021-06-07 14:04 UTC, jjcarstens commented on lib/nerves_ssh/exec.ex
> +      {:error, {_, :erl_scan, cause}} -> {:error, :erl_scan.format_error(cause)}
```suggestion
      {:error, {_anno_location, _mod, cause}, _location} -> {:error, :erl_scan.format_error(cause)}
```

2021-06-07 23:41 UTC, jjcarstens approved these changes

2021-06-08 00:09 UTC, fhunleth commented
I updated the unit test to work with the current way where both the shell and the exec need to be specified. See #33. 

This seems like a lot of code to maintain and I'm not feeling like debugging dialyzer to push it over the finish line.

2021-06-08 00:09 UTC, closed without merging